"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const checkoutController_1 = require("../controllers/checkoutController");
const checkoutInteractor_1 = require("../../application/interactor/checkoutInteractor");
const checkoutModel_1 = require("../../infrastructure/model/checkoutModel");
const cartRepo_1 = require("../../infrastructure/repositories/cartRepo");
const cartModel_1 = require("../../infrastructure/model/cartModel");
const productRepository_1 = require("../../infrastructure/repositories/productRepository");
const producModel_1 = require("../../infrastructure/model/producModel");
const checkoutRepository_1 = require("../../infrastructure/repositories/checkoutRepository");
const StripeGateway_1 = require("../../infrastructure/paymentGateways/StripeGateway");
const TabbytPaymentGateway_1 = require("../../infrastructure/paymentGateways/TabbytPaymentGateway");
const TamaraGateway_1 = require("../../infrastructure/paymentGateways/TamaraGateway");
const checkoutRepo = new checkoutRepository_1.CheckoutRepository(checkoutModel_1.CheckoutModel);
const cartRepo = new cartRepo_1.CartRepository(cartModel_1.CartModel);
const productRepo = new productRepository_1.ProductRepository(producModel_1.ProductModel);
const stripePayment = new StripeGateway_1.StripePaymentGateway();
const tabbyPayment = new TabbytPaymentGateway_1.TabbyPaymentGateway();
const tamarPayment = new TamaraGateway_1.TamaraPaymentGateway();
const checkoutInteractor = new checkoutInteractor_1.CheckoutInteractor(cartRepo, checkoutRepo, productRepo, stripePayment, tabbyPayment);
const checkoutController = new checkoutController_1.CheckoutController(checkoutInteractor);
const checkoutRoutes = express_1.default.Router();
checkoutRoutes.post("/", checkoutController.checkout.bind(checkoutController));
checkoutRoutes.get("/", checkoutController.getSecretKey.bind(checkoutController));
checkoutRoutes.post("/verify-payment", checkoutController.verifyPayment.bind(checkoutController));
exports.default = checkoutRoutes;
//# sourceMappingURL=checkoutRoute.js.map